GLOBAL.TUNING.WHIP_USES = 250
GLOBAL.TUNING.WHIP_DAMAGE = 17
GLOBAL.TUNING.WHIP_RANGE = 3
GLOBAL.TUNING.WHIP_SUPERCRACK_RANGE = 14
GLOBAL.TUNING.WHIP_SUPERCRACK_EPIC_CHANCE = .2
GLOBAL.TUNING.WHIP_SUPERCRACK_MONSTER_CHANCE = .4
GLOBAL.TUNING.WHIP_SUPERCRACK_CREATURE_CHANCE = .5